name: food
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: 2.2.16
  flutter_test:
    sdk: flutter

flutter_native_splash:
  background_image: "assets/images/splash_screen.png"
  web: false
  ios: true
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/recipe/
    - assets/images/user/

  fonts:
    - family: FoodIcons
      fonts:
        - asset: assets/fonts/FoodIcons.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
